# Generated by Django 2.2.1 on 2019-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_listing_useraccount_userfinancial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
